name: Publish PyPI Release

on:
  release:
    types: [published]

jobs:
  build-dists:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: "3.12"

      - run: python -m pip install build

      - name: Build Dists
        run: python -m build .

      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: packages
          path: dist/*

  publish_pypi:
    needs: [build-dists]
    runs-on: ubuntu-latest
    environment: publish-pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: packages
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@81e9d935c883d0b210363ab89cf05f3894778450 # v1.8.14
