name: Publish Test PyPI Release

on:
  push:
    tags: ["*"]

jobs:
  build-dists:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: "3.12"

      - run: python -m pip install build

      - name: Set dev version prior to upload
        run: python ./scripts/set_dev_version.py

      - name: Build Dists
        run: python -m build .

      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: packages
          path: dist/*

  publish:
    needs: [build-dists]
    runs-on: ubuntu-latest
    environment: publish-test-pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: packages
          path: dist

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@8a08d616893759ef8e1aa1f2785787c0b97e20d6 # v1.10.0
        with:
          repository-url: https://test.pypi.org/legacy/
